# your domain
domain: example.com # or example.com:9443 for reserve proxy server
port:                 # default 12580

only-node: true

# source list file
source-files:
  # use local file
  - source.yaml
#  - https://raw.githubusercontent.com/asdlokj1qpi23/subrule/main/tg.yaml
  #- tgchannel.yaml
  #- webfuzz.yaml
  #- clash.yaml
  #- sub.yaml
  #- tony.yaml
  #- rxsweet.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  ======= #

#====Postgresql database info ====#
database_url: ""

#==== Interval between each crawling ====#
crawl-interval: 360           # v0.5.x default 60 (minutes)
#crontime:                  # v0.4.x default 60 (minutes). Deprecated in the newest version
healthcheck-timeout: 5        # default 5 (seconds)
healthcheck-connection: 50 # default 500. The number of health check connections simultaneously

#==== Speed test ====#
speedtest: false # default false. Warning: this will consume large network resources.
speedtest-interval:         # default 720 (min)
speed-timeout:              # default 10 (seconds).
speed-connection:           # v0.7.2 default 5. The number of speed test connections simultaneously
#connection                 # v0.7.1 and beblow

#==== Active proxy speed test ====#
active-interval: 60            # default 60 (min)
active-frequency:           # default 100 (requests per interval)
active-max-number:          # default 100. If more than this number of active proxies, the extra will be deprecated by speed

#==== Cloudflare api ====#
cf_email: ""
cf_key: ""

#==== stream test support disney+ and netflix ====
stream-max-connect: 50 # v0.7.14 default 500
netflix-test: false # v0.7.14 default false
disney-test: false # v0.7.14 default false